### PR TITLE
Migrate to graphics-core20

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Note, it would be convenient to land this first: https://github.com/MirServer/mir-kiosk-snap-launch/pull/10

(There's no dependency on the changes, but this will need rebuilding to pick up the improvements.)

**Comment by Saviq** [comment]
Am I doing something wrong?

```plain
2021-07-26T12:05:19Z systemd[1]: Started Service for snap application mir-kiosk-neverputt.daemon.
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544483]: + snapctl get daemon
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + [ true = true ]
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + exec /snap/mir-kiosk-neverputt/138/bin/wayland-launch /snap/mir-kiosk-neverputt/138/usr/games/neverputt
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + snapctl is-connected wayland
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544494]: + dirname /run/user/0/snap.mir-kiosk-neverputt
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + real_xdg_runtime_dir=/run/user/0
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + real_wayland=/run/user/0/wayland-0
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + [ ! -O /run/user/0/wayland-0 ]
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + mkdir -p /run/user/0/snap.mir-kiosk-neverputt -m 700
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + ln -sf /run/user/0/wayland-0 /run/user/0/snap.mir-kiosk-neverputt
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + ln -sf /run/user/0/wayland-0.lock /run/user/0/snap.mir-kiosk-neverputt
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + unset DISPLAY
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: + exec /snap/mir-kiosk-neverputt/138/usr/games/neverputt
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: Failed to create secure directory (/var/run/pulse): Permission denied
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: Failure to open audio device (ALSA: Couldn't open audio device: No such file or directory)
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: Creating a window (800x600, fullscreen)
2021-07-26T12:05:19Z mir-kiosk-neverputt.daemon[544460]: Failure to create window (Could not load EGL library)
```

```plain
$ snap connections mir-kiosk-neverputt
Interface                 Plug                                  Slot                         Notes
audio-playback            mir-kiosk-neverputt:audio-playback    :audio-playback              -
content[graphics-core20]  mir-kiosk-neverputt:graphics-core20   mesa-core20:graphics-core20  -
hardware-observe          mir-kiosk-neverputt:hardware-observe  :hardware-observe            manual
opengl                    mir-kiosk-neverputt:opengl            :opengl                      -
wayland                   mir-kiosk-neverputt:wayland           :wayland                     manual
```

**Comment by AlanGriffiths** [comment]
> Am I doing something wrong?

No. I get the same after nuking the build VM.

**Comment by AlanGriffiths** [comment]
@Saviq fixed

**Comment by AlanGriffiths** [comment]
Unfixed in favour of https://github.com/MirServer/mesa-core20/pull/9

Marking "draft" as the mesa-core20 changes needs merging and promoting to stable before this works.

**Comment by AlanGriffiths** [comment]
> Marking "draft" as the mesa-core20 changes needs merging and promoting to stable before this works.

Done, ready for review

**Review by Saviq — APPROVED** [review]
Yup.

bors merge

**Pull request merged**
